# Generated by Django 4.2 on 2024-02-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название заказа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('budget', models.CharField(max_length=20, verbose_name='Желаемый бюджет')),
                ('deadline', models.CharField(max_length=20, verbose_name='Желаемый срок')),
                ('status', models.CharField(choices=[('consideration', 'На рассмотрении'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='consideration', max_length=20, verbose_name='Статус')),
                ('files', models.FileField(upload_to='uploads/', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
