# Generated by Django 5.0 on 2024-02-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ordercreate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercreate',
            name='files',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Файлы'),
        ),
    ]
