# Generated by Django 4.2 on 2024-02-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_ordercreate_options_alter_ordercreate_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercreate',
            name='targetgroup',
            field=models.CharField(default=1, max_length=50, verbose_name='Целевая аудитория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercreate',
            name='websitetype',
            field=models.CharField(choices=[('', 'Выберите тип сайта'), ('1', 'Интернет-магазин'), ('2', 'Персональный сайт'), ('3', 'Сайты-визитка'), ('4', 'Форум'), ('5', 'Блог'), ('6', 'Лендинг'), ('7', 'Другой')], default=1, max_length=20, verbose_name='Желаемый срок'),
            preserve_default=False,
        ),
    ]
