# Generated by Django 4.2 on 2024-02-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ordercreate_targetgroup_ordercreate_websitetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercreate',
            name='websitetype',
            field=models.CharField(choices=[('', 'Выберите тип сайта'), ('1', 'Интернет-магазин'), ('2', 'Персональный сайт'), ('3', 'Сайты-визитка'), ('4', 'Форум'), ('5', 'Блог'), ('6', 'Лендинг'), ('7', 'Другой')], max_length=20, verbose_name='Тип сайта'),
        ),
    ]
