# Generated by Django 4.2 on 2024-03-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_ordercreate_deadline_alter_ordercreate_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercreate',
            name='deadline',
            field=models.CharField(choices=[('', 'Выберите желаемый срок'), ('1', '30 Дней'), ('2', '45 Дней'), ('3', '60 Дней'), ('4', '75 Дней')], max_length=20, verbose_name='Желаемый срок'),
        ),
    ]
