# Generated by Django 4.2 on 2024-03-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_ordercreate_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercreate',
            name='socialnetwork',
            field=models.CharField(default=0, max_length=50, verbose_name='Контакт для связи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercreate',
            name='socialnetworkchose',
            field=models.CharField(choices=[('', 'Выберите тип связи'), ('1', 'Telegram'), ('2', 'Facebook'), ('3', 'WhatsApp'), ('4', 'Номер телефона'), ('5', 'Свой')], default=1, max_length=20, verbose_name='Тип связи'),
            preserve_default=False,
        ),
    ]
